# Generated by Django 5.0.7 on 2024-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_payment_user_payment_email_payment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
