# Generated by Django 5.0.8 on 2024-11-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_payment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flutterwave_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
