# Generated by Django 5.1 on 2024-11-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_payment_flutterwave_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('successful', 'Successfully Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
